[package]
name = "godotpcktool-gui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "godotpcktool-gui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
godotpck-rs = { path = "../pck" }

eframe = "0.27"
egui = "0.27"
rfd = "0.14"
